default_language_version:
    python: python3
repos:
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          - --remove-all-unused-imports
          - --in-place
          - --ignore-init-module-imports
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        pass_filenames: false
        entry: poetry run mypy .
        args:
          - --install-types
          - --non-interactive
          - --strict
          - --show-error-codes
-   repo:  https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
        stages:
          - manual
